[package]
name = "fast-watcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
rusqlite = { version = "0.37.0", features = ["bundled"] }
